### ISSUE TITLE
Productionize Chainhooks

### ISSUE THREAD

**Issue by smcclellan** [hirosystems/chainhook#343]
Parent ticket for chainhooks to be productionized. These are the remaining steps:

- [x] https://github.com/hirosystems/chainhook/issues/317
- [x] https://github.com/hirosystems/chainhook/issues/210
- [x] https://github.com/hirosystems/devops/issues/1257
- [x] https://github.com/hirosystems/devops/issues/1256
- [x] https://github.com/hirosystems/devops/issues/1262
- [x] https://github.com/hirosystems/chainhook/issues/288

Nice to have:
- [ ] https://github.com/hirosystems/chainhook/issues/287
- [ ] https://github.com/hirosystems/chainhook/issues/286
- [x] https://github.com/hirosystems/devops/issues/1305

Dependency:
- [x] https://github.com/hirosystems/clarinet/issues/1078

**Comment by smcclellan** [comment]
Marking this Completed & will track the Nice To Haves separately.
