### ISSUE TITLE
Tracking state of Chainhook Alarming

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/chainhook#562]
### Chainhook side
The `/ping`  or `/status` endpoint should expose:
- [x] Highest Bitcoin block height received (regardless if it is being connected to a fork)
- [x] Highest Bitcoin block height connected
- [x] Highest Bitcoin block height evaluated for predicates
- [x] Bitcoin Predicate Evaluation Lag (Highest Bitcoin block connected - Highest Bitcoin block evaluated for predicates)
- [x] Bitcoin Canonical Fork Lag (Highest Bitcoin block received - Highest Bitcoin block connected)
- [x] Highest Stacks block height received (regardless if it is being connected to a fork)
- [x] Highest Stacks block height connected
- [x] Highest Stacks block height evaluated for predicates
- [x] Stacks Predicate Evaluation Lag (Highest Stacks block connected - Highest Stacks block evaluated for predicates)
- [x] Stacks Canonical Fork Lag (Highest Stacks block received - Highest Stacks block connected)

### Devops side (ticketed separately)
We want to trigger our alarming when:
- [ ] Bitcoin Predicate Evaluation Lag  > 1
- [ ] Bitcoin Canonical Fork Lag > 1
- [ ] bitcoind.block_height - chainhook.bitcoin.block_height > 1
- [ ] Stacks Predicate Evaluation Lag > 1
- [ ] Stacks Canonical Fork Lag > 1
- [ ] stacks_node.block_height - chainhook.stacks.block_height > 1

**Comment by smcclellan** [comment]
DevOps side tracked [here](https://github.com/hirosystems/devops/issues/1676).
